<?php
/*********************************************************************************
 * This file is part of SpiceCRM. SpiceCRM is an enhancement of SugarCRM Community Edition
 * and is developed by aac services k.s.. All rights are (c) 2016 by aac services k.s.
 * You can contact us at info@spicecrm.io
 * 
 * SpiceCRM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 * 
 * SpiceCRM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ********************************************************************************/
namespace SpiceCRM\modules\Employees;

use SpiceCRM\data\BeanFactory;
use SpiceCRM\includes\SugarObjects\templates\person\Person;

class Employee extends Person {

	public function __construct() {
		parent::__construct();
		$this->emailAddress = BeanFactory::getBean('EmailAddresses');
	}

    public function retrieveViewDetails()
    {
        parent::retrieveViewDetails(); // TODO: Change the autogenerated stub
        // get primary orgunit
        $primaryOrgUnit = $this->getPrimaryOrgUnit();
        if($primaryOrgUnit){
            $this->orgunit_id = $primaryOrgUnit->id;
            $this->orgunit_name = $primaryOrgUnit->name;
        }
    }

    /**
     * return the primary orgunit object for the employee
     * @return false|mixed
     */
    public function getPrimaryOrgUnit(){
        $orgunit = $this->get_linked_beans('orgunitprimary');
        if(count($orgunit) > 0){
            return $orgunit[0];
        }

        // BWC fallback check employees.orgunit_id
        if(!empty($this->orgunit_id)){
            $orgunit = BeanFactory::getBean('OrgUnits', $this->orgunit_id);
            return $orgunit;
        }

        return false;
    }

    /**
     * return the user assigned of the primary orgunit object for the employee
     * @return false|mixed
     */
    public function getManagerPrimaryOrgUnit(){
        $orgunit = $this->getPrimaryOrgUnit();
        if($orgunit){
            $manager = BeanFactory::getBean('Users', $orgunit->assigned_user_id);
            if($manager){
                return $manager;
            }
        }
        return false;
    }


}
